### ISSUE TITLE
Shouldn't try to create a database that already exists

### ISSUE THREAD

**Issue by fugue88** [atomicjolt/adhesion#117]
While running `rake db:setup`:

```
[app1] Couldn't create database for {"adapter"=>"postgresql", "host"=>"192.168.13.20", "encoding"=>"unicode", "database"=>"adhesion_production", "pool"=>5, "username"=>"adhesion", "password"=>"xxx", "template"=>"template0"}
```

**Comment by bfcoder** [comment]
```sh
$ rake db:setup
adhesion_development already exists
```
It does recognize that the database already exists, not sure what you have misconfigured.

**Comment by bfcoder** [comment]
```sh
RAILS_ENV=production rake db:setup
adhesion_production already exists
```
Same result with production.

**Comment by bfcoder** [comment]
Closing as this is something that we can't control. Rails tries to create the database, but your limited user doesn't have permissions to do that. Just need to use `rake db:schema:load` and `rake db:seed` instead.
